FROM python:3.11-slim
WORKDIR /app
COPY order-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared ./shared
COPY order-service/app.py .
EXPOSE 5002
CMD ["python", "app.py"]
