FROM otel/opentelemetry-collector-contrib:latest AS collector

FROM alpine:3.20
COPY --from=collector /otelcol-contrib /otelcol-contrib
COPY collector-entrypoint.sh /etc/otelcol/collector-entrypoint.sh
ENTRYPOINT ["/bin/sh", "/etc/otelcol/collector-entrypoint.sh"]
