apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: ecommerce-poc
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    exporters:
      debug:
      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: "otel"
    
    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
          unit: "ms"
        dimensions:
          - name: http.status_code
          - name: http.method
          - name: http.route
    
    processors:
      tail_sampling:
        decision_wait: 5s
        num_traces: 100
        expected_new_traces_per_sec: 50
        policies:
          - name: errors
            type: status_code
            status_code:
              status_codes:
                - ERROR
          - name: successful-trace-sample
            type: probabilistic
            probabilistic:
              sampling_percentage: 100
      batch:
    
    service:
      pipelines:
        traces/spanmetrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [spanmetrics]
        traces/tail:
          receivers: [otlp]
          processors: [tail_sampling, batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [batch]
          exporters: [prometheus]
